### ISSUE TITLE
Configuring which compiler to use

### ISSUE THREAD

**Issue by ashalkhakov** [sparverius/ats-acc#7]
The list of `whichcc` has to be extended with Temptory compiler (tempacc).

Maybe make this configurable via an environment variable or some such?

**Comment by sparverius** [comment]
There is a separate branch for temptory. 
To install, checkout the temptory branch.
[Temptory Version](https://github.com/sparverius/ats-acc/tree/temptory)

Also, have been working on porting it so that it can be compiled by tempopt (just been working on other things).

**Comment by ashalkhakov** [comment]
Thanks, it works. :)
